//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostProduct
    {
        public int PostID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime RowInsertTime { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Product Product { get; set; }
    }
}
